# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoEditorMusicSlide' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoEditorMusicSlide
pod 'ALProgressView'
pod 'MTTransitions'
pod "ABVideoRangeSlider"

end
